version: '3'  # version of compose format 

services:
  appGenerator:
    build: ./Generator  # path is relative to docker-compose.yml location
    volumes:
      - ./Generator:/appGenerator # mount point
    ports:
      - 5000:80  # host:container
  
  appOCR:
    build: ./Ocr  # path is relative to docker-compose.yml location
    volumes:
      - ./Ocr:/appOCR # mount point
    ports:
      - 5001:80  # host:container
    depends_on:
      - appGenerator  # appOCR is not going to work unless appGenerator is running

  appClient:
    build: ./Client  # path is relative to docker-compose.yml location
    volumes:
      - ./Client:/app # mount point
    ports:
      - 5002:80  # host:container
    depends_on:
      - appOCR  # appClient is not going to work unless appOCR is running
  