version: '3'  # version of compose format 

services:
  app_generator:
    build: ./Generator  # path is relative to docker-compose.yml location
    volumes:
      - ./Generator:/app_generator # mount point
    ports:
      - 5000:80  # host:container
  
  app_ocr:
    build: ./Ocr  # path is relative to docker-compose.yml location
    volumes:
      - ./Ocr:/app_ocr # mount point
    ports:
      - 5001:80  # host:container
    depends_on:
      - app_generator  # appOCR is not going to work unless appGenerator is running

  app_client:
    build: ./Client  # path is relative to docker-compose.yml location
    volumes:
      - ./Client:/app_client # mount point
    ports:
      - 5002:80  # host:container
    depends_on:
      - app_ocr  # appClient is not going to work unless appOCR is running
  