version: '3'  # version of compose format 

services:
  app_generator:
    build: ./Generator  
    volumes:
      - ./Generator:/app_generator 
    ports:
      - 5000:80  
  
  app_ocr:
    build: ./Ocr  
    volumes:
      - ./Ocr:/app_ocr 
    ports:
      - 5001:80  
    depends_on:
      - app_generator  

  app_client:
    build: ./Client  
    volumes:
      - ./Client:/app_client 
    ports:
      - 5002:80  
    depends_on:
      - app_ocr 